version: '3.8'

services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin123
      - INFLUXDB_HTTP_AUTH_ENABLED=true
    volumes:
      - influxdb_data:/var/lib/influxdb
    networks:
      - k6-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - influxdb
    networks:
      - k6-network

  k6:
    image: grafana/k6:latest
    container_name: k6-runner
    volumes:
      - ./scripts:/scripts
      - ./config:/config
      - ./results:/results
    environment:
      - K6_OUT=influxdb=http://admin:admin123@influxdb:8086/k6
    depends_on:
      - influxdb
    networks:
      - k6-network
    stdin_open: true
    tty: true

volumes:
  influxdb_data:
  grafana_data:

networks:
  k6-network:
    driver: bridge